In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/Pratik/DS/premier-league-ml/data/raw/PremierLeague.csv")

In [4]:
df.head()

,MatchID,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,...,MarketMaxAwayTeam,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1

In [5]:
df.tail()

,MatchID,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,...,MarketMaxAwayTeam,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints
12155,2024-2025_Newcastle_Everton,2024-2025,38,2025-05-25,16:00,Newcastle,Everton,0,1,A,...,9.50,1.32,5.60,8.77,1.53,2.65,1.50,2.55,0,3
12156,2024-2025_Nott'm Forest_Chelsea,2024-2025,38,2025-05-25,16:00,Nott'm Forest,Chelsea,0,1,A,...,2.25,3.09,3.72,2.20,1.72,2.26,1.67,2.21,0,3
12157,2024-2025_Southampton_Arsenal,2024-2025,38,2025-05-25,16:00,Southampton,Arsenal,1,2,A,...,1.31,9.45,5.83,1.29,1.50,2.80,1.47,2.64,0,3
12158,2024-2025_Tottenham_Brighton,2024-2025,38,2025-05-25,16:00,Tottenham,Brighton,1,4,A,...,1.73,4.23,4.43,1.71,1.34,3.55,1.32,3.34,0,3
12159,2024-2025_Wolves_Brentford,2024-2025,38,2025-05-25,16:00,Wolves,Brentford,1,1,D,...,2.48,2.71,3.76,2.43,1.53,2.63,1.50,2.55,1,1

In [6]:
df.info()
# Convert Date → datetime in data_prep.py
# Rest of the formats feel okay

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12160 entries, 0 to 12159
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MatchID                 12160 non-null  object
 1   Season                  12160 non-null  object
 2   MatchWeek               12160 non-null  int64
 3   Date                    12160 non-null  object
 4   Time                    2280 non-null   object
 5   HomeTeam                12160 non-null  object
 6   AwayTeam                12160 non-null  object
 7   FullTimeHomeTeamGoals   12160 non-null  int64
 8   FullTimeAwayTeamGoals   12160 non-null  int64
 9   FullTimeResult          12160 non-null  object
 10  HalfTimeHomeTeamGoals   11400 non-null  float64
 11  HalfTimeAwayTeamGoals   11400 non-null  float64
 12  HalfTimeResult          11400 non-null  object
 13  Referee                 9500 non-null   object
 14  HomeTeamShots           9500 non-null   float64
 15  AwayTeamShots           9500 non-null   float64
 16  HomeTeamShotsOnTarget   9500 non-null   float64
 17  AwayTeamShotsOnTarget   9500 non-null   float64
 18  HomeTeamCorners         9500 non-null   float64
 19  AwayTeamCorners         9500 non-null   float64
 20  HomeTeamFouls           9500 non-null   float64
 21  AwayTeamFouls           9500 non-null   float64
 22  HomeTeamYellowCards     9500 non-null   float64
 23  AwayTeamYellowCards     9500 non-null   float64
 24  HomeTeamRedCards        9500 non-null   float64
 25  AwayTeamRedCards        9500 non-null   float64
 26  B365HomeTeam            8740 non-null   float64
 27  B365Draw                8740 non-null   float64
 28  B365AwayTeam            8740 non-null   float64
 29  B365Over2.5Goals        3283 non-null   float64
 30  B365Under2.5Goals       3283 non-null   float64
 31  MarketMaxHomeTeam       2280 non-null   float64
 32  MarketMaxDraw           2280 non-null   float64
 33  MarketMaxAwayTeam       2280 non-null   float64
 34  MarketAvgHomeTeam       2280 non-null   float64
 35  MarketAvgDraw           2280 non-null   float64
 36  MarketAvgAwayTeam       2280 non-null   float64
 37  MarketMaxOver2.5Goals   2280 non-null   float64
 38  MarketMaxUnder2.5Goals  2280 non-null   float64
 39  MarketAvgOver2.5Goals   2280 non-null   float64
 40  MarketAvgUnder2.5Goals  2280 non-null   float64
 41  HomeTeamPoints          12160 non-null  int64
 42  AwayTeamPoints          12160 non-null  int64
dtypes: float64(29), int64(5), object(9)
memory usage: 4.0+ MB

In [7]:
df[(df['Date'] > '2018-08-01') & (df['Date'] < '2025-08-01')].isnull().sum()
# No missing values in the date range of interest atleast from columns which is of interest

MatchID                     0
Season                      0
MatchWeek                   0
Date                        0
Time                      380
HomeTeam                    0
AwayTeam                    0
FullTimeHomeTeamGoals       0
FullTimeAwayTeamGoals       0
FullTimeResult              0
HalfTimeHomeTeamGoals       0
HalfTimeAwayTeamGoals       0
HalfTimeResult              0
Referee                     0
HomeTeamShots               0
AwayTeamShots               0
HomeTeamShotsOnTarget       0
AwayTeamShotsOnTarget       0
HomeTeamCorners             0
AwayTeamCorners             0
HomeTeamFouls               0
AwayTeamFouls               0
HomeTeamYellowCards         0
AwayTeamYellowCards         0
HomeTeamRedCards            0
AwayTeamRedCards            0
B365HomeTeam                0
B365Draw                    0
B365AwayTeam                0
B365Over2.5Goals          381
B365Under2.5Goals         381
MarketMaxHomeTeam         380
MarketMaxDraw             380
MarketMaxAwayTeam         380
MarketAvgHomeTeam         380
MarketAvgDraw             380
MarketAvgAwayTeam         380
MarketMaxOver2.5Goals     380
MarketMaxUnder2.5Goals    380
MarketAvgOver2.5Goals     380
MarketAvgUnder2.5Goals    380
HomeTeamPoints              0
AwayTeamPoints              0
dtype: int64

In [8]:
df[(df['Date'] > '2018-08-01') & (df['Date'] < '2025-08-01')].duplicated().sum()
# No duplicate rows in the date range of interest

np.int64(0)

In [9]:
df.duplicated(subset=['MatchID']).sum()  
# No duplicate MatchIDs

np.int64(0)

In [10]:
df['MatchID'].notna().all()   
# True would mean every row has a non-NA value
# which should mean every match has a MatchID, and every row is valid & has a match

np.True_

In [11]:
df.sample(10)
# Checking random samples for any anomalies

,MatchID,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,...,MarketMaxAwayTeam,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints
8794,2016-2017_Middlesbrough_Tottenham,2016-2017,6,2016-09-24,NaN,Middlesbrough,Tottenham,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
4219,2004-2005_Aston Villa_Chelsea,2004-2005,5,2004-09-11,NaN,Aston Villa,Chelsea,0,0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
6995,2011-2012_Aston Villa_Liverpool,2011-2012,16,2011-12-18,NaN,Aston Villa,Liverpool,0,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
2803,2000-2001_Man City_Ipswich,2000-2001,14,2000-11-25,NaN,Man City,Ipswich,2,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
2474,1999-2000_Chelsea_Sheffield Weds,1999-2000,18,1999-12-29,NaN,Chelsea,Sheffield Weds,3,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4579,2005-2006_Chelsea_Arsenal,2005-2006,2,2005-08-21,NaN,Chelsea,Arsenal,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
1708,1997-1998_Arsenal_Leicester,1997-1998,17,1997-12-26,NaN,Arsenal,Leicester,2,1,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
11826,2024-2025_Leicester_Wolves,2024-2025,17,2024-12-22,14:00,Leicester,Wolves,0,3,A,...,2.75,2.55,3.56,2.69,1.72,2.31,1.66,2.24,0,3
8257,2014-2015_West Ham_Chelsea,2014-2015,28,2015-03-04,NaN,West Ham,Chelsea,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
6105,2009-2010_Liverpool_Aston Villa,2009-2010,3,2009-08-24,NaN,Liverpool,Aston Villa,1,3,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3

In [12]:
df_date = df[(df['Date'] > '2018-08-01') & (df['Date'] < '2025-08-01')].copy() ## I’m inspecting the subset of interest, not preparing it.
df_matchweek = df_date[['MatchWeek']].drop_duplicates().copy()
df_matchweek.astype(int).value_counts()

# This was to check if the season 18/19 had 38 matchweeks
# It does, so data seems good
# Similarly, other seasons can be checked if needed
# Some seasons may have compressed schedules due to COVID-19 etc. but they still will have 38 matchweeks

MatchWeek
1            1
2            1
3            1
4            1
5            1
6            1
7            1
8            1
9            1
10           1
11           1
12           1
13           1
14           1
15           1
16           1
17           1
18           1
19           1
20           1
21           1
22           1
23           1
24           1
25           1
26           1
27           1
28           1
29           1
30           1
31           1
32           1
33           1
34           1
35           1
36           1
37           1
38           1
Name: count, dtype: int64

In [13]:
column_list = df.columns.tolist()
column_list
# listing all columns names for reference
# All B365 contains bookmaker odds and will be dropped due to leakage.

['MatchID',
 'Season',
 'MatchWeek',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FullTimeHomeTeamGoals',
 'FullTimeAwayTeamGoals',
 'FullTimeResult',
 'HalfTimeHomeTeamGoals',
 'HalfTimeAwayTeamGoals',
 'HalfTimeResult',
 'Referee',
 'HomeTeamShots',
 'AwayTeamShots',
 'HomeTeamShotsOnTarget',
 'AwayTeamShotsOnTarget',
 'HomeTeamCorners',
 'AwayTeamCorners',
 'HomeTeamFouls',
 'AwayTeamFouls',
 'HomeTeamYellowCards',
 'AwayTeamYellowCards',
 'HomeTeamRedCards',
 'AwayTeamRedCards',
 'B365HomeTeam',
 'B365Draw',
 'B365AwayTeam',
 'B365Over2.5Goals',
 'B365Under2.5Goals',
 'MarketMaxHomeTeam',
 'MarketMaxDraw',
 'MarketMaxAwayTeam',
 'MarketAvgHomeTeam',
 'MarketAvgDraw',
 'MarketAvgAwayTeam',
 'MarketMaxOver2.5Goals',
 'MarketMaxUnder2.5Goals',
 'MarketAvgOver2.5Goals',
 'MarketAvgUnder2.5Goals',
 'HomeTeamPoints',
 'AwayTeamPoints']

In [14]:
df['Is_Correct'] = (df['FullTimeHomeTeamGoals'] > df['FullTimeAwayTeamGoals']) == (df['FullTimeResult'] == 'H') # Checking if FullTimeResult is consistent with the goals scored
all_valid = df['Is_Correct'].all()
all_valid  # True means all rows are consistent

np.True_

In [15]:
# Home Away symmetry check
home_teams = set(df['HomeTeam'].unique())
away_teams = set(df['AwayTeam'].unique())
home_teams == away_teams  # True if both have the same unique team names

True

In [16]:
# Check if Man City name stays consistent throughout the dataset
'Man City' in home_teams and 'Man City' in away_teams

True

In [ ]:
df['HomeTeam'].unique() 
# Checking unique team names for any inconsistencies
# Example: Wether the dataset contains Man City & Manchester City as home team names
# Does not seem to have any such issues

array(['Arsenal', 'Aston Villa', 'Chelsea', 'Liverpool', 'Man City',
       'Newcastle', 'Oldham', 'Sheffield United', 'Southampton',
       'West Ham', 'Norwich', 'Tottenham', 'Everton', 'Ipswich', 'Leeds',
       'Wimbledon', 'Blackburn', 'Coventry', 'Man United', 'QPR',
       'Sheffield Weds', 'Swindon', 'Crystal Palace', 'Leicester',
       "Nott'm Forest", 'Bolton', 'Middlesbrough', 'Derby', 'Sunderland',
       'Barnsley', 'Charlton', 'Watford', 'Bradford', 'Fulham',
       'Birmingham', 'West Brom', 'Portsmouth', 'Wolves', 'Wigan',
       'Reading', 'Hull', 'Stoke', 'Burnley', 'Blackpool', 'Swansea',
       'Cardiff', 'Bournemouth', 'Brighton', 'Huddersfield', 'Brentford',
       'Luton'], dtype=object)

In [ ]:
df['AwayTeam'].unique()  # Checking similarly for away teams

array(['Coventry', 'QPR', 'Blackburn', 'Sheffield Weds', 'Leeds',
       'Tottenham', 'Ipswich', 'Swindon', 'Everton', 'Wimbledon',
       'Man United', 'Arsenal', 'Man City', 'Southampton', 'West Ham',
       'Chelsea', 'Norwich', 'Newcastle', 'Sheffield United', 'Liverpool',
       'Aston Villa', 'Oldham', "Nott'm Forest", 'Leicester',
       'Crystal Palace', 'Bolton', 'Middlesbrough', 'Sunderland', 'Derby',
       'Barnsley', 'Charlton', 'Bradford', 'Watford', 'Fulham',
       'West Brom', 'Birmingham', 'Wolves', 'Portsmouth', 'Wigan',
       'Reading', 'Stoke', 'Hull', 'Burnley', 'Blackpool', 'Swansea',
       'Cardiff', 'Bournemouth', 'Huddersfield', 'Brighton', 'Brentford',
       'Luton'], dtype=object)

Most of the format is okay, just need to change date while prepping data. No missing values for the columns which are important for the date range. There are no duplicate rows or matches, all matchids are valid, all seasons have all matchweeks, the results are consistent with goals scored, all the team names are unique & there are no inconsistencies of using different abbreviations for same team.